#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiOn3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyLop")]
	public partial class DataQuanLyClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSuKien(SuKien instance);
    partial void UpdateSuKien(SuKien instance);
    partial void DeleteSuKien(SuKien instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    #endregion
		
		public DataQuanLyClassDataContext() : 
				base(global::BaiOn3.Properties.Settings.Default.QuanLyLopConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ThamGia> ThamGias
		{
			get
			{
				return this.GetTable<ThamGia>();
			}
		}
		
		public System.Data.Linq.Table<SuKien> SuKiens
		{
			get
			{
				return this.GetTable<SuKien>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suaLop")]
		public int suaLop([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LopID", DbType="Int")] System.Nullable<int> lopID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LopMa", DbType="VarChar(8)")] string lopMa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LopTen", DbType="NVarChar(200)")] string lopTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoSinhVien", DbType="Int")] System.Nullable<int> soSinhVien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lopID, lopMa, lopTen, soSinhVien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suaSinhVien")]
		public int suaSinhVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienID", DbType="Int")] System.Nullable<int> sinhvienID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSSV", DbType="VarChar(8)")] string mSSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienHo", DbType="NVarChar(100)")] string sinhvienHo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienTen", DbType="NVarChar(100)")] string sinhvienTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienNgaySinh", DbType="Date")] System.Nullable<System.DateTime> sinhvienNgaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienSDT", DbType="VarChar(13)")] string sinhvienSDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienEmail", DbType="NVarChar(500)")] string sinhvienEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LopID", DbType="Int")] System.Nullable<int> lopID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sinhvienID, mSSV, sinhvienHo, sinhvienTen, sinhvienNgaySinh, sinhvienSDT, sinhvienEmail, lopID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themLop")]
		public int themLop([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LopMa", DbType="VarChar(8)")] string lopMa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LopTen", DbType="NVarChar(200)")] string lopTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoSinhVien", DbType="Int")] System.Nullable<int> soSinhVien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lopMa, lopTen, soSinhVien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themSinhvien")]
		public int themSinhvien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSSV", DbType="VarChar(8)")] string mSSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienHo", DbType="NVarChar(100)")] string sinhvienHo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienTen", DbType="NVarChar(100)")] string sinhvienTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienNgaySinh", DbType="Date")] System.Nullable<System.DateTime> sinhvienNgaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienSDT", DbType="VarChar(13)")] string sinhvienSDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SinhvienEmail", DbType="NVarChar(500)")] string sinhvienEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LopID", DbType="Int")] System.Nullable<int> lopID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mSSV, sinhvienHo, sinhvienTen, sinhvienNgaySinh, sinhvienSDT, sinhvienEmail, lopID);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThamGia")]
	public partial class ThamGia
	{
		
		private System.Nullable<int> _SinhvienID;
		
		private System.Nullable<int> _SukienID;
		
		public ThamGia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinhvienID", DbType="Int")]
		public System.Nullable<int> SinhvienID
		{
			get
			{
				return this._SinhvienID;
			}
			set
			{
				if ((this._SinhvienID != value))
				{
					this._SinhvienID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SukienID", DbType="Int")]
		public System.Nullable<int> SukienID
		{
			get
			{
				return this._SukienID;
			}
			set
			{
				if ((this._SukienID != value))
				{
					this._SukienID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuKien")]
	public partial class SuKien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SukienID;
		
		private string _SukienTen;
		
		private System.Nullable<System.DateTime> _SukienTimeStart;
		
		private System.Nullable<System.DateTime> _SukienTimeEnd;
		
		private string _SukienDiadiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSukienIDChanging(int value);
    partial void OnSukienIDChanged();
    partial void OnSukienTenChanging(string value);
    partial void OnSukienTenChanged();
    partial void OnSukienTimeStartChanging(System.Nullable<System.DateTime> value);
    partial void OnSukienTimeStartChanged();
    partial void OnSukienTimeEndChanging(System.Nullable<System.DateTime> value);
    partial void OnSukienTimeEndChanged();
    partial void OnSukienDiadiemChanging(string value);
    partial void OnSukienDiadiemChanged();
    #endregion
		
		public SuKien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SukienID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SukienID
		{
			get
			{
				return this._SukienID;
			}
			set
			{
				if ((this._SukienID != value))
				{
					this.OnSukienIDChanging(value);
					this.SendPropertyChanging();
					this._SukienID = value;
					this.SendPropertyChanged("SukienID");
					this.OnSukienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SukienTen", DbType="NVarChar(500)")]
		public string SukienTen
		{
			get
			{
				return this._SukienTen;
			}
			set
			{
				if ((this._SukienTen != value))
				{
					this.OnSukienTenChanging(value);
					this.SendPropertyChanging();
					this._SukienTen = value;
					this.SendPropertyChanged("SukienTen");
					this.OnSukienTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SukienTimeStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> SukienTimeStart
		{
			get
			{
				return this._SukienTimeStart;
			}
			set
			{
				if ((this._SukienTimeStart != value))
				{
					this.OnSukienTimeStartChanging(value);
					this.SendPropertyChanging();
					this._SukienTimeStart = value;
					this.SendPropertyChanged("SukienTimeStart");
					this.OnSukienTimeStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SukienTimeEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> SukienTimeEnd
		{
			get
			{
				return this._SukienTimeEnd;
			}
			set
			{
				if ((this._SukienTimeEnd != value))
				{
					this.OnSukienTimeEndChanging(value);
					this.SendPropertyChanging();
					this._SukienTimeEnd = value;
					this.SendPropertyChanged("SukienTimeEnd");
					this.OnSukienTimeEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SukienDiadiem", DbType="NVarChar(500)")]
		public string SukienDiadiem
		{
			get
			{
				return this._SukienDiadiem;
			}
			set
			{
				if ((this._SukienDiadiem != value))
				{
					this.OnSukienDiadiemChanging(value);
					this.SendPropertyChanging();
					this._SukienDiadiem = value;
					this.SendPropertyChanged("SukienDiadiem");
					this.OnSukienDiadiemChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SinhvienID;
		
		private string _MSSV;
		
		private string _SinhvienHo;
		
		private string _SinhvienTen;
		
		private System.Nullable<System.DateTime> _SinhvienNgaySinh;
		
		private string _SinhvienEmail;
		
		private System.Nullable<int> _SinhvienStatus;
		
		private System.Nullable<int> _LopID;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSinhvienIDChanging(int value);
    partial void OnSinhvienIDChanged();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OnSinhvienHoChanging(string value);
    partial void OnSinhvienHoChanged();
    partial void OnSinhvienTenChanging(string value);
    partial void OnSinhvienTenChanged();
    partial void OnSinhvienNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnSinhvienNgaySinhChanged();
    partial void OnSinhvienEmailChanging(string value);
    partial void OnSinhvienEmailChanged();
    partial void OnSinhvienStatusChanging(System.Nullable<int> value);
    partial void OnSinhvienStatusChanged();
    partial void OnLopIDChanging(System.Nullable<int> value);
    partial void OnLopIDChanged();
    #endregion
		
		public SinhVien()
		{
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinhvienID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SinhvienID
		{
			get
			{
				return this._SinhvienID;
			}
			set
			{
				if ((this._SinhvienID != value))
				{
					this.OnSinhvienIDChanging(value);
					this.SendPropertyChanging();
					this._SinhvienID = value;
					this.SendPropertyChanged("SinhvienID");
					this.OnSinhvienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="VarChar(8)")]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinhvienHo", DbType="NVarChar(100)")]
		public string SinhvienHo
		{
			get
			{
				return this._SinhvienHo;
			}
			set
			{
				if ((this._SinhvienHo != value))
				{
					this.OnSinhvienHoChanging(value);
					this.SendPropertyChanging();
					this._SinhvienHo = value;
					this.SendPropertyChanged("SinhvienHo");
					this.OnSinhvienHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinhvienTen", DbType="NVarChar(100)")]
		public string SinhvienTen
		{
			get
			{
				return this._SinhvienTen;
			}
			set
			{
				if ((this._SinhvienTen != value))
				{
					this.OnSinhvienTenChanging(value);
					this.SendPropertyChanging();
					this._SinhvienTen = value;
					this.SendPropertyChanged("SinhvienTen");
					this.OnSinhvienTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinhvienNgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> SinhvienNgaySinh
		{
			get
			{
				return this._SinhvienNgaySinh;
			}
			set
			{
				if ((this._SinhvienNgaySinh != value))
				{
					this.OnSinhvienNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._SinhvienNgaySinh = value;
					this.SendPropertyChanged("SinhvienNgaySinh");
					this.OnSinhvienNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinhvienEmail", DbType="NVarChar(500)")]
		public string SinhvienEmail
		{
			get
			{
				return this._SinhvienEmail;
			}
			set
			{
				if ((this._SinhvienEmail != value))
				{
					this.OnSinhvienEmailChanging(value);
					this.SendPropertyChanging();
					this._SinhvienEmail = value;
					this.SendPropertyChanged("SinhvienEmail");
					this.OnSinhvienEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinhvienStatus", DbType="Int")]
		public System.Nullable<int> SinhvienStatus
		{
			get
			{
				return this._SinhvienStatus;
			}
			set
			{
				if ((this._SinhvienStatus != value))
				{
					this.OnSinhvienStatusChanging(value);
					this.SendPropertyChanging();
					this._SinhvienStatus = value;
					this.SendPropertyChanged("SinhvienStatus");
					this.OnSinhvienStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LopID", DbType="Int")]
		public System.Nullable<int> LopID
		{
			get
			{
				return this._LopID;
			}
			set
			{
				if ((this._LopID != value))
				{
					if (this._Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLopIDChanging(value);
					this.SendPropertyChanging();
					this._LopID = value;
					this.SendPropertyChanged("LopID");
					this.OnLopIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_SinhVien", Storage="_Lop", ThisKey="LopID", OtherKey="LopID", IsForeignKey=true)]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._LopID = value.LopID;
					}
					else
					{
						this._LopID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lop")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LopID;
		
		private string _LopMa;
		
		private string _LopTen;
		
		private System.Nullable<int> _SoSinhVien;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLopIDChanging(int value);
    partial void OnLopIDChanged();
    partial void OnLopMaChanging(string value);
    partial void OnLopMaChanged();
    partial void OnLopTenChanging(string value);
    partial void OnLopTenChanged();
    partial void OnSoSinhVienChanging(System.Nullable<int> value);
    partial void OnSoSinhVienChanged();
    #endregion
		
		public Lop()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LopID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LopID
		{
			get
			{
				return this._LopID;
			}
			set
			{
				if ((this._LopID != value))
				{
					this.OnLopIDChanging(value);
					this.SendPropertyChanging();
					this._LopID = value;
					this.SendPropertyChanged("LopID");
					this.OnLopIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LopMa", DbType="VarChar(8)")]
		public string LopMa
		{
			get
			{
				return this._LopMa;
			}
			set
			{
				if ((this._LopMa != value))
				{
					this.OnLopMaChanging(value);
					this.SendPropertyChanging();
					this._LopMa = value;
					this.SendPropertyChanged("LopMa");
					this.OnLopMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LopTen", DbType="NVarChar(200)")]
		public string LopTen
		{
			get
			{
				return this._LopTen;
			}
			set
			{
				if ((this._LopTen != value))
				{
					this.OnLopTenChanging(value);
					this.SendPropertyChanging();
					this._LopTen = value;
					this.SendPropertyChanged("LopTen");
					this.OnLopTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSinhVien", DbType="Int")]
		public System.Nullable<int> SoSinhVien
		{
			get
			{
				return this._SoSinhVien;
			}
			set
			{
				if ((this._SoSinhVien != value))
				{
					this.OnSoSinhVienChanging(value);
					this.SendPropertyChanging();
					this._SoSinhVien = value;
					this.SendPropertyChanged("SoSinhVien");
					this.OnSoSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_SinhVien", Storage="_SinhViens", ThisKey="LopID", OtherKey="LopID")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = null;
		}
	}
}
#pragma warning restore 1591
